// <auto-generated />
namespace MVCPresentation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddedUserIDfieldtomatchusersbetweenwebanddesktop : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedUserIDfieldtomatchusersbetweenwebanddesktop));
        
        string IMigrationMetadata.Id
        {
            get { return "202203250157474_Added UserID field to match users between web and desktop."; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
